version: '3.7'

services:

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - /etc/letsencrypt/:/etc/letsencrypt/
      - /etc/ssl/certs/dhparam.pem:/etc/ssl/certs/dhparam.pem
      - ./nginx/options-ssl-nginx.conf:/etc/options-ssl-nginx.conf
    container_name: nginx
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    restart: unless-stopped
    depends_on:
      - app

  app:
    container_name: app
    #image:  doublebyte/ivaucher-frontend:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    # ports:
    #   - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
